image:
  - Visual Studio 2019
  - Ubuntu
  - macos
clone_depth: 1
for:
  -
    matrix:
      only:
        - image: Ubuntu
    environment:
      APPVEYOR_SSH_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJDW/+oYNGOiPvwuwAL9tc/LQgg58aosIVpMYfepQZ20V+VZnHpZh8IRDA8Jo5xht19p2PksA+hFgqA0kpKtrSkuiWdE8rATQItfk4gf7yB0yGasJGGQZYazy9k/9XtmYkq2HHOOeEqdxvrICddJQ88MLCLT9lJENSUP/YS/yGcjZFXVxE11pTeIcqlCRU+3eYa1v7BeNvXIKNhZoK5orXWrtuH3cy8jrSns/u70aYfJ6B2jA8CnWnDbuvpeQtEY61SQqlKUsSArNa8NAsXj41wr3Ar9gAG9330w7EMTqlutk8HZO35uHI0q5qinUhaQYufPPrVkb2L/N+ZCfu0fnh appveyor"
      APPIMAGE_TOOL: appimagetool-x86_64.AppImage
      PYTHON_APPIMAGE: python3.7.13-cp37-cp37m-manylinux2014_x86_64.AppImage
      DEPLOY_DIR: AppDir/opt/pyfa
#      APPVEYOR_SSH_BLOCK: true
    cache:
      - /home/appveyor/.cache/pip -> requirements.txt
    install:
      - sh: git fetch --prune --unshallow # to fix the version dump issues
      - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get -y update
      - sh: sudo DEBIAN_FRONTEND=noninteractive apt-get -y install python3.7-dev libgtk-3-dev python3-pip libwebkit2gtk-4.0-dev
    before_build:
      - sh: mkdir build && cd build
      - sh: curl -LO https://github.com/AppImage/AppImageKit/releases/download/13/$APPIMAGE_TOOL && chmod +x $APPIMAGE_TOOL
      - sh: curl -LO https://github.com/niess/python-appimage/releases/download/python3.7/$PYTHON_APPIMAGE && chmod +x $PYTHON_APPIMAGE
    build_script:
      # Prepare Python base AppImage, stripping Python metadata
      - sh: ./$PYTHON_APPIMAGE --appimage-extract
      - sh: mv squashfs-root AppDir
      - sh: rm AppDir/python*.desktop
      - sh: rm AppDir/usr/share/applications/*.desktop
      - sh: rm AppDir/usr/share/metainfo/*.appdata.xml
      - sh: unlink AppDir/AppRun
      - sh: mkdir -p $DEPLOY_DIR
      # run install pyfa packages and any other requirements
      - sh: AppDir/usr/bin/python -s -m pip install -U pip setuptools==41.6.0 wheel pathlib2
      - sh: AppDir/usr/bin/python -s -m pip install wxPython==4.0.6
